// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: ozonmp/srv_review_api/v1/srv_review_api.proto

package srv_review_api

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Review with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Review) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Review with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in ReviewMultiError, or nil if none found.
func (m *Review) ValidateAll() error {
	return m.validate(true)
}

func (m *Review) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Foo

	if all {
		switch v := interface{}(m.GetCreated()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ReviewValidationError{
					field:  "Created",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ReviewValidationError{
					field:  "Created",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreated()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ReviewValidationError{
				field:  "Created",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ReviewMultiError(errors)
	}
	return nil
}

// ReviewMultiError is an error wrapping multiple validation errors returned by
// Review.ValidateAll() if the designated constraints aren't met.
type ReviewMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ReviewMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ReviewMultiError) AllErrors() []error { return m }

// ReviewValidationError is the validation error returned by Review.Validate if
// the designated constraints aren't met.
type ReviewValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ReviewValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ReviewValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ReviewValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ReviewValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ReviewValidationError) ErrorName() string { return "ReviewValidationError" }

// Error satisfies the builtin error interface
func (e ReviewValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sReview.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ReviewValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ReviewValidationError{}

// Validate checks the field values on DescribeReviewV1Request with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DescribeReviewV1Request) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DescribeReviewV1Request with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DescribeReviewV1RequestMultiError, or nil if none found.
func (m *DescribeReviewV1Request) ValidateAll() error {
	return m.validate(true)
}

func (m *DescribeReviewV1Request) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetReviewId() <= 0 {
		err := DescribeReviewV1RequestValidationError{
			field:  "ReviewId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return DescribeReviewV1RequestMultiError(errors)
	}
	return nil
}

// DescribeReviewV1RequestMultiError is an error wrapping multiple validation
// errors returned by DescribeReviewV1Request.ValidateAll() if the designated
// constraints aren't met.
type DescribeReviewV1RequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DescribeReviewV1RequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DescribeReviewV1RequestMultiError) AllErrors() []error { return m }

// DescribeReviewV1RequestValidationError is the validation error returned by
// DescribeReviewV1Request.Validate if the designated constraints aren't met.
type DescribeReviewV1RequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DescribeReviewV1RequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DescribeReviewV1RequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DescribeReviewV1RequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DescribeReviewV1RequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DescribeReviewV1RequestValidationError) ErrorName() string {
	return "DescribeReviewV1RequestValidationError"
}

// Error satisfies the builtin error interface
func (e DescribeReviewV1RequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDescribeReviewV1Request.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DescribeReviewV1RequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DescribeReviewV1RequestValidationError{}

// Validate checks the field values on DescribeReviewV1Response with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DescribeReviewV1Response) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DescribeReviewV1Response with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DescribeReviewV1ResponseMultiError, or nil if none found.
func (m *DescribeReviewV1Response) ValidateAll() error {
	return m.validate(true)
}

func (m *DescribeReviewV1Response) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetValue()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, DescribeReviewV1ResponseValidationError{
					field:  "Value",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, DescribeReviewV1ResponseValidationError{
					field:  "Value",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetValue()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DescribeReviewV1ResponseValidationError{
				field:  "Value",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return DescribeReviewV1ResponseMultiError(errors)
	}
	return nil
}

// DescribeReviewV1ResponseMultiError is an error wrapping multiple validation
// errors returned by DescribeReviewV1Response.ValidateAll() if the designated
// constraints aren't met.
type DescribeReviewV1ResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DescribeReviewV1ResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DescribeReviewV1ResponseMultiError) AllErrors() []error { return m }

// DescribeReviewV1ResponseValidationError is the validation error returned by
// DescribeReviewV1Response.Validate if the designated constraints aren't met.
type DescribeReviewV1ResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DescribeReviewV1ResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DescribeReviewV1ResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DescribeReviewV1ResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DescribeReviewV1ResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DescribeReviewV1ResponseValidationError) ErrorName() string {
	return "DescribeReviewV1ResponseValidationError"
}

// Error satisfies the builtin error interface
func (e DescribeReviewV1ResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDescribeReviewV1Response.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DescribeReviewV1ResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DescribeReviewV1ResponseValidationError{}
