// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package srv_review_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SrvReviewApiServiceClient is the client API for SrvReviewApiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SrvReviewApiServiceClient interface {
	// DescribeReviewV1 - Describe a review
	DescribeReviewV1(ctx context.Context, in *DescribeReviewV1Request, opts ...grpc.CallOption) (*DescribeReviewV1Response, error)
}

type srvReviewApiServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSrvReviewApiServiceClient(cc grpc.ClientConnInterface) SrvReviewApiServiceClient {
	return &srvReviewApiServiceClient{cc}
}

func (c *srvReviewApiServiceClient) DescribeReviewV1(ctx context.Context, in *DescribeReviewV1Request, opts ...grpc.CallOption) (*DescribeReviewV1Response, error) {
	out := new(DescribeReviewV1Response)
	err := c.cc.Invoke(ctx, "/ozonmp.srv_review_api.v1.SrvReviewApiService/DescribeReviewV1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SrvReviewApiServiceServer is the server API for SrvReviewApiService service.
// All implementations must embed UnimplementedSrvReviewApiServiceServer
// for forward compatibility
type SrvReviewApiServiceServer interface {
	// DescribeReviewV1 - Describe a review
	DescribeReviewV1(context.Context, *DescribeReviewV1Request) (*DescribeReviewV1Response, error)
	mustEmbedUnimplementedSrvReviewApiServiceServer()
}

// UnimplementedSrvReviewApiServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSrvReviewApiServiceServer struct {
}

func (UnimplementedSrvReviewApiServiceServer) DescribeReviewV1(context.Context, *DescribeReviewV1Request) (*DescribeReviewV1Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DescribeReviewV1 not implemented")
}
func (UnimplementedSrvReviewApiServiceServer) mustEmbedUnimplementedSrvReviewApiServiceServer() {}

// UnsafeSrvReviewApiServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SrvReviewApiServiceServer will
// result in compilation errors.
type UnsafeSrvReviewApiServiceServer interface {
	mustEmbedUnimplementedSrvReviewApiServiceServer()
}

func RegisterSrvReviewApiServiceServer(s grpc.ServiceRegistrar, srv SrvReviewApiServiceServer) {
	s.RegisterService(&SrvReviewApiService_ServiceDesc, srv)
}

func _SrvReviewApiService_DescribeReviewV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeReviewV1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SrvReviewApiServiceServer).DescribeReviewV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ozonmp.srv_review_api.v1.SrvReviewApiService/DescribeReviewV1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SrvReviewApiServiceServer).DescribeReviewV1(ctx, req.(*DescribeReviewV1Request))
	}
	return interceptor(ctx, in, info, handler)
}

// SrvReviewApiService_ServiceDesc is the grpc.ServiceDesc for SrvReviewApiService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SrvReviewApiService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ozonmp.srv_review_api.v1.SrvReviewApiService",
	HandlerType: (*SrvReviewApiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DescribeReviewV1",
			Handler:    _SrvReviewApiService_DescribeReviewV1_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ozonmp/srv_review_api/v1/srv_review_api.proto",
}
